/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IosRouteImport } from './routes/ios'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCharmIdRouteImport } from './routes/app/$charmId'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as PoliciesSlugRouteImport } from './routes/policies/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as TCodeRouteImport } from './routes/t.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IosRoute = IosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCharmIdRoute = AppCharmIdRouteImport.update({
  id: '/app/$charmId',
  path: '/app/$charmId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ios': typeof IosRoute
  '/squad': typeof SquadRoute
  '/app/$charmId': typeof AppCharmIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/t/$code': typeof TCodeRoute
  '/app/': typeof AppIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ios': typeof IosRoute
  '/squad': typeof SquadRoute
  '/app/$charmId': typeof AppCharmIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/t/$code': typeof TCodeRoute
  '/app': typeof AppIndexRoute
  '/journal': typeof JournalIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ios': typeof IosRoute
  '/squad': typeof SquadRoute
  '/app/$charmId': typeof AppCharmIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/t/$code': typeof TCodeRoute
  '/app/': typeof AppIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/ios'
    | '/squad'
    | '/app/$charmId'
    | '/journal/$slug'
    | '/policies/$slug'
    | '/shop/$slug'
    | '/t/$code'
    | '/app/'
    | '/journal/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/ios'
    | '/squad'
    | '/app/$charmId'
    | '/journal/$slug'
    | '/policies/$slug'
    | '/shop/$slug'
    | '/t/$code'
    | '/app'
    | '/journal'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/ios'
    | '/squad'
    | '/app/$charmId'
    | '/journal/$slug'
    | '/policies/$slug'
    | '/shop/$slug'
    | '/t/$code'
    | '/app/'
    | '/journal/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IosRoute: typeof IosRoute
  SquadRoute: typeof SquadRoute
  AppCharmIdRoute: typeof AppCharmIdRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  TCodeRoute: typeof TCodeRoute
  AppIndexRoute: typeof AppIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios': {
      id: '/ios'
      path: '/ios'
      fullPath: '/ios'
      preLoaderRoute: typeof IosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$charmId': {
      id: '/app/$charmId'
      path: '/app/$charmId'
      fullPath: '/app/$charmId'
      preLoaderRoute: typeof AppCharmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  IosRoute: IosRoute,
  SquadRoute: SquadRoute,
  AppCharmIdRoute: AppCharmIdRoute,
  JournalSlugRoute: JournalSlugRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  TCodeRoute: TCodeRoute,
  AppIndexRoute: AppIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
